#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# SpectroPhenoClimatron EyePI documentation build configuration file, created by
# sphinx-quickstart on Thu Dec  8 12:53:48 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.doctest',
              'sphinx.ext.intersphinx',
              'sphinx.ext.todo',
              'sphinx.ext.coverage',
              'sphinx.ext.mathjax',
              'sphinx.ext.viewcode',
              # 'sphinx_autodoc_typehints',
              'sphinx.ext.githubpages'
              # 'sphinxcontrib.fulltoc'
              ]

# Add any paths that contain templates here, relative to this directory.

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
# source_suffix = '.rst'

from recommonmark.parser import CommonMarkParser

parsers = {
    '.md': CommonMarkParser,
}

source_suffix = ['.rst', ".md"]

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'SPC-EyePi'
copyright = '2016, Gareth Dunstone, Kevin Murray, Tim Brown'
author = 'Gareth Dunstone, Kevin Murray, Tim Brown'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '3.2'
# The full version, including alpha/beta/rc tags.
release = '3.2'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'localtoc.html',
        # 'relations.html',
        'searchbox.html'
    ]
}
html_theme_options = {
    'description': "Capture/Control software for DSLRs, USB cameras, and the Raspberry Pi camera.",
    'github_repo': "spc-eyepi",
    'github_user': "borevitzlab",
    'github_button': True,
    'github_type': 'star',
    'fixed_sidebar': True,
    'sidebar_includehidden': True
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['../_static']
templates_path = ['./_templates']

html_show_sourcelink = False
html_add_permalinks = u"§"

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'SpectroPhenoClimatronEyePidoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'SpectroPhenoClimatronEyePI.tex', 'SpectroPhenoClimatron EyePI Documentation',
     'Gareth Dunstone, Kevin Murray, Tim Brown', 'manual'),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc,
     'spectrophenoclimatroneyepi',
     'SpectroPhenoClimatron EyePI Documentation',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'SpectroPhenoClimatronEyePI', 'SpectroPhenoClimatron EyePI Documentation',
     author, 'SpectroPhenoClimatronEyePI', 'One line description of project.',
     'Miscellaneous'),
]

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    # '': ('', None),
    'python': ('https://docs.python.org/3.5', None),
    'numpy': ('http://numpy.readthedocs.io/en/latest/', None),
    'pyudev': ('https://pyudev.readthedocs.io/en/latest/', None),
    'flask': ('http://flask.pocoo.org/docs/0.12/', None),
    'flask_bcrypt': ('https://flask-bcrypt.readthedocs.io/en/latest/', None),
    'picamera': ("http://picamera.readthedocs.io/en/release-1.12/", None)
}
